config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: [:new, :create, :index]
  root to: "pages#home"

  devise_for :users
  resources :users do
    resources :gears, only: [:new, :create]
    resources :messages, only: [:new, :create, :index]
    resources :rentals, only: [:index] do
      resources :reviews, only: %i[new create]
    end
    get "my_gear", to: "dashboard#my_gear", as: :my_gear
  end
  resources :reviews, only: [:destroy, :edit, :update]

  get '/users/:id/host_show', to: 'rentals#host_show', as: :host_show

  resources :gears, only: :show
  resources :gears, only: :index do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:destroy, :edit, :update]
  resources :gears, only: [:destroy, :edit, :update]
  get "dashboard", to: "dashboard#show", as: :dashboard
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_user, only: [:show, :my_gear]

  def show
    @gears = Gear.all
    @rentals = Rental.where(user: @user)
  end

  def my_gear
    @rentals_by_me = Rental.where(user: @user)
    @rentals_by_me_pc = @rentals_by_me.select { |rental| (rental.status == "pending" || rental.status == "confirmed") }
    @rentals_hosted_by_me = Rental.select { |rental| rental.gear.user == current_user && rental.status }
    @rentals_completed_as_renter = Rental.where(user: @user, status: "completed")
    @rentals_completed_as_host = Rental.where(user: @user, status: "completed")
    @gears = Gear.where(user: @user)

    #1. Gears listed by me, rented by others
    rentals_v1 = Rental.select { |rental| (rental.gear.user_id == current_user.id && (rental.status == "pending" ||  rental.status == "confirmed")) || rental.user_id == current_user.id}
    @map_gears_all = Gear.where(id: rentals_v1.map(&:gear_id))

    @markers = @map_gears_all.geocoded.map do |gear|
      {
        lat: gear.latitude,
        lng: gear.longitude,
        info_window: render_to_string(partial: "info_window", locals: {gear: gear}),
        image_url: helpers.asset_url("green_marker.png")
      }
    end
  end

  private

  def set_user
    @user = current_user
  end
end

app/views/dashboard/_info_window.html.erb
Gear name: <a class="map-pop-up-text" href="<%= gear_path(gear) %>"><%= gear.gear_name %></a><br>
Gear type: <%= gear.gear_type %><br>
Host name: <a class="map-pop-up-text" href="<%= user_path(gear.user_id) %>"><%= User.find(gear.user_id).first_name %> <%= User.find(gear.user_id).last_name %></a>

app/views/dashboard/_personal_gear_card.html.erb
	<% gears.each do |gear| %>
    <div class="col-3">
      <div class="product-card">
        <a href= <%= gear_path(gear) %> target="_top">
        <div class="product-tumb">
          <% if gear.photos.present? %>
            <p class="hover-text">See More</p>
            <%= cl_image_tag gear.photos.first.key, crop: :fill %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1628087235616-4e146afcd061?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80" alt="">
          <% end %>
        </div>
        <div class="product-details">
          <div class="flex-container">
            <div class="product-catagory"><%= gear.gear_type %></div>
            <div class="product-rating"><span>★</span> <%= rand(3.9..5.0).round(1) %></div>
          </div>
          <h4><%= gear.gear_name %></h4>
          <p class="product-summary"><%= gear.summary %></p>
          <p>Capacity: <%= gear.total_occupancy %></p>
          <div class="product-bottom-details">
            <div class="product-price">$<%= gear.price.round %> <small> per night</small></div>
          </div>
        </div>
      </a>
    </div>
  </div>
<% end %>

app/views/dashboard/_personal_rentals_card.html.erb
<% rentals.each do |rental| %>
    <div class="col-6">
      <div class="product-card">
        <a href= <%= gear_path(rental.gear_id) %> target="_top">
        <div class="product-tumb">
          <% if rental.gear.photos.present? %>
            <%= cl_image_tag rental.gear.photos.first.key, crop: :fill %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1628087235616-4e146afcd061?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80" alt="">
          <% end %>
        </div>
        <div class="product-details">
        <div class="d-flex justify-content-between align-middle flex-nowrap">
          <div>
          <span class="product-catagory"><%= rental.start_date %> - <%= rental.end_date %></span>
          </div>
          <div class="col-4 text-end">
            <% if rental.status == "pending" %>
              <% if rental.user_id == current_user.id %>
                <%= link_to edit_rental_path(rental), class: 'btn btn-sm border text-right' do %>
                    <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
              <% else %>
                <%= link_to rental_path(rental, rental: { status: 'confirmed' }),
                  class: 'btn btn-sm border text-right',
                  data: { turbo_method: :patch, turbo_confirm: "Are you sure you want to confirm this rental?" } do %>
                  <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
              <% end %>

              <%= link_to rental_path(rental, rental: { status: 'cancelled' }),
              class: 'btn btn-sm border text-right',
              data: { turbo_method: :patch, turbo_confirm: "Are you sure you want to cancel this rental?" } do %>
                <i class="fa-regular fa-trash-can"></i>
              <% end %>
            <% end %>

            <% if rental.status == "comfirmed" %>
              <%= link_to rental_path(rental, rental: { status: 'cancelled' }),
              class: 'btn btn-sm border text-right',
              data: { turbo_method: :patch, turbo_confirm: "Are you sure you want to cancel this rental?" } do %>
                <i class="fa-regular fa-trash-can"></i>
              <% end %>
            <% end %>

            <% if  rental.status == "completed"%>
              <%= link_to new_user_rental_review_path(user_id: r.user_id, rental_id: r.id),
                class: 'btn btn-light btn-sm border text-right' do %>
                  <i class="fa-regular fa-comment"></i>
                <% end %>
            <% end %>

          </div>
        </div>

          <span class="product-catagory"><%= rental.gear.gear_type %></span>
          <h4><%= rental.gear.gear_name %></h4>
          <p><%= rental.gear.summary %></p>
          <p>Capacity: <%= rental.gear.total_occupancy %></p>
          <div class="product-bottom-details d-flex justify-content-between align-middle flex-nowrap">
            <div class="product-price">$<%= rental.total.round %> <small> Total</small></div>
            <div class="product-price text-end pr-3"><small><%= rental.status %></small></div>
          </div>
        </div>
      </a>
    </div>
  </div>
<% end %>

app/views/dashboard/my_gear.html.erb
<div class="container">
  <h2 class="text-center">My rentals and gears</h2>
  <br>
  <div class="map-container rounded-lg">
    <div class="row">
      <div class="col w-100 map-render"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>
<br>

<br>
<div class="container mb-3 border-bottom pb-5">
  <div class="row">
    <div class="col">
      <h2 class="text-center">Rentals by me</h2>
      <br>
      <% if @rentals_by_me.empty? %>
        <h4 class="body-text text-center">Nothing rented so far!</h4>
      <% else %>
        <div class="row">
          <%= render "personal_rentals_card", rentals: @rentals_by_me_pc %>
        </div>
      <% end %>
    </div>
    <div class="col">
      <h2 class="text-center">Rentals hosted by me</h2>
      <br>
      <% if @rentals_hosted_by_me.empty? %>
        <h4 class="body-text text-center">No gears rented out yet!</h4>
      <% else %>
        <div class="row">
          <%= render "personal_rentals_card", rentals: @rentals_hosted_by_me %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>
<div class="container">
  <h2 class="body-text text-center">My Gears</h2>
  <br>
  <div class="container">
    <div class="row gx-5">
      <%= render "personal_gear_card", gears: @gears %>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="container">
  <h1>All Gears for Rent</h1><br>
  --------------------------
  <% @gears.each do |gear| %>
    <% if gear.user != current_user %>
      <li>
        Gear Type:<%= gear.gear_type %> <br>
        Summary:<%= gear.summary %> <br>
        Owner:<%= gear.user.first_name %> <br>
        $<%= gear.price %> <br>
        <%= link_to "See More", gear_path(gear) %> <br>
        --------------------------
      </li>
    <% end %>
  <% end %>

  <br>
  --------------------------
  <h1>Rentals I have hosted</h1>
  <%= link_to "View rentals I have hosted", host_show_path(current_user) %> <br>
  --------------------------
  <h1>Your Pending/Active Rentals</h1>
  --------------------------
  <% @rentals.each do |rental| %>

    <li></li>
      <strong>Summary:</strong>
      <br>
      <%= rental.gear.summary %>
      <br>
      --------------------------
      <br>
      <strong>Price</strong>
      <br>
      Price Per day: <%= rental.price %>
      <br>
      Total Price: <%= rental.total %>
      <br>
      --------------------------
      <br>
      <strong>Dates</strong>
      <br>
      Start Date:<%= rental.start_date %>
      <br>
      End Date:<%= rental.end_date %>
      <br>
      --------------------------
      <br>
      Status:
      <%= rental.status ? "Confirmed" : "Pending confirmation"%>
      <br>
      --------------------------
      <br>
    </li>
  <% end %> <br>
  <%= link_to "View all rentals", user_rentals_path(current_user) %>
  <br>
  --------------------------

  <br>


  <h3>Currently logged in as:</h3>
  <p><%= @user.first_name %> <%= @user.last_name %></p>
  <p><%= @user.email %></p>
</div>
<div>
</div>