config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: [:new, :create, :index]
  root to: "pages#home"

  devise_for :users
  resources :users do
    resources :gears, only: [:new, :create]
    resources :messages, only: [:new, :create, :index]
    resources :rentals, only: [:index] do
      resources :reviews, only: %i[new create]
    end
    get "my_gear", to: "dashboard#my_gear", as: :my_gear
  end
  resources :reviews, only: [:destroy, :edit, :update]

  get '/users/:id/host_show', to: 'rentals#host_show', as: :host_show

  resources :gears, only: :show
  resources :gears, only: :index do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:destroy, :edit, :update]
  resources :gears, only: [:destroy, :edit, :update]
  get "dashboard", to: "dashboard#show", as: :dashboard
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  validates :sender_id, presence: true
  validates :recipient_id, presence: true
  validates :recipient_id, exclusion: { in: lambda{ |message| [message.sender_id] } }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    parties = [current_user.id, params[:user_id].to_i]

    @messages = Message.select do |message|
      parties.include?(message.sender_id) && parties.include?(message.recipient_id)
    end

    @user = User.find(params[:user_id])
    @message = Message.new
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @user = User.find(params[:user_id])
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @user = User.find(params[:user_id])
    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    @message.recipient_id = @user.id

    respond_to do |format|
      if @message.save
        # format.html { redirect_to user_messages_path(@user), notice: "Message was successfully created." }
        format.json { render :index, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:sender_id, :recipient_id, :content)
    end
end

app/views/messages/_form.html.erb
<%= simple_form_for [@user, @message] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.hidden_field :sender_id %>
    <%= f.input :content,
                input_html: { class: 'form-transparent'} %>

  </div>

  <div class="form-actions">
    <%= f.button :submit,
    class: "button-green w-100" %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Sender:</strong>
    <%= message.sender_id %>
  </p>

  <p>
    <strong>Recipient:</strong>
    <%= message.recipient_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= message.content %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<%# <p style="color: green"><%= notice %>

<div class="container">
<h1>Message <%=  %></h1>

<div class="messages">
  <ul>
    <% @messages.each do |message| %>
      <% if message.sender_id == current_user.id %>
				<li class="replies">
					<img src="http://emilcarlsson.se/assets/mikeross.png" alt="" />
					<p><%= message.content.capitalize %></p>
				</li>
      <% else %>
				<li class="sent">
					<img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
					<p><%= message.content.capitalize %></p>
				</li>
      <% end %>
    <% end %>
  </ul>
</div>

<%= render "form", message: @message %>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>
<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", user_messages_path(@user) %>
</div>

app/views/messages/show.html.erb
<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", user_messages_path(@user) %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>