config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: [:new, :create, :index]
  root to: "pages#home"

  devise_for :users
  resources :users do
    resources :gears, only: [:new, :create]
    resources :messages, only: [:new, :create, :index]
    resources :rentals, only: [:index] do
      resources :reviews, only: %i[new create]
    end
    get "my_gear", to: "dashboard#my_gear", as: :my_gear
  end
  resources :reviews, only: [:destroy, :edit, :update]

  get '/users/:id/host_show', to: 'rentals#host_show', as: :host_show

  resources :gears, only: :show
  resources :gears, only: :index do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:destroy, :edit, :update]
  resources :gears, only: [:destroy, :edit, :update]
  get "dashboard", to: "dashboard#show", as: :dashboard
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :gears, dependent: :destroy
  has_many :rentals, dependent: :destroy

  has_one_attached :avatar
  has_many :reviews, through: :rentals, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @gears = Gear.where(user: @user)
  end
end

app/views/users/show.html.erb
<div class="container d-flex justify-content-between">
  <div class="user-info d-flex flex-column justify-content-between">

    <%# user name and avatar %>
    <div class="d-flex flex-column">
      <div class="section-div pb-2">
        <h3><%= "Hi, I'm #{@user.first_name.capitalize}" %></h3>
        <% if current_user.present? && current_user.avatar.present? %>
          <%= cl_image_tag current_user.avatar.key, crop: :fill, class:"avatar-large" %>
        <% else %>
          <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png" alt="mdo" width="32" height="32" class="rounded-circle">
        <% end %>
      </div>
        <%# user location TO ADD TO USER MODEL %>
        <div class="d-flex align-items-center">
          <i class="fa-solid fa-location-dot"></i>
          <p class="mb-0 mx-2"> <%= @user.location %> </p>
        </div>
    </div>

    <div>
      <h5>About me:</h5>
      <p><%= @user.description %></p>
    </div>

    <% if @user != current_user %>
      <%= link_to  'Start Chat', user_messages_path(@user), class: "button" %>
    <% end %>
  </div>

  <div class="listings">
    <h3><%= "#{@user.first_name.capitalize}'s listings:" %></h3>
    <div>
      <% if @gears.empty? %>
        <p> <%= "#{@user.first_name.capitalize} does not have any listings yet." %> </p>
      <% else %>
        <%= render "components/gear_list", gears: @gears %>
      <% end %>
    </div>
  </div>

</div>