config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: [:new, :create, :index]
  root to: "pages#home"

  devise_for :users
  resources :users do
    resources :gears, only: [:new, :create]
    resources :messages, only: [:new, :create, :index]
    resources :rentals, only: [:index] do
      resources :reviews, only: %i[new create]
    end
    get "my_gear", to: "dashboard#my_gear", as: :my_gear
  end
  resources :reviews, only: [:destroy, :edit, :update]

  get '/users/:id/host_show', to: 'rentals#host_show', as: :host_show

  resources :gears, only: :show
  resources :gears, only: :index do
    resources :rentals, only: [:new, :create]
  end
  resources :rentals, only: [:destroy, :edit, :update]
  resources :gears, only: [:destroy, :edit, :update]
  get "dashboard", to: "dashboard#show", as: :dashboard
end

app/models/gear.rb
class Gear < ApplicationRecord
  include PgSearch::Model
  belongs_to :user

  pg_search_scope :search_by_gear_attribute,
    against: [ :gear_type, :gear_name, :summary ],
    using: {
      tsearch: { prefix: true }
    }

  has_many :rentals, dependent: :destroy
  has_many :reviews, through: :rentals, dependent: :destroy
  has_many_attached :photos

  # validates :gear_name, presence: true
  validates :gear_type, presence: true
  validates :gear_type, inclusion: { in: %w(Hiking Rock-Climbing Cooking Sleeping Kayak Navigation Shelter Sleeping-Bags Hydration Navigation First-Aid Survival Illumination Repair-Kits) }
  validates :address, presence: true
  validates :price, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_user, only: [:create, :new, :index, :update, :edit, :destroy]

  def index
    @gears = Gear.all

    if params[:query].present?
      sql_query = <<~SQL
        gears.gear_name @@ :query
        OR gears.gear_type @@ :query
        OR gears.summary @@ :query
      SQL
      @gears = Gear.all.where(sql_query, query: "%#{params[:query]}%")
    else
      @gears = Gear.all
    end
  end

  def new
    @gear = Gear.new
  end

  def show
    @gear = Gear.find(params[:id])
    @rental = Rental.new
  end

  def create
    @gear = Gear.new(gear_params)
    @gear.user = @user
    if @gear.save
      redirect_to user_my_gear_path(@user), status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @gear = Gear.find(params[:id])
    if @gear.update(gear_params)
      redirect_to user_my_gear_path(@user), notice: "Gear was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @gear = Gear.find(params[:id])
  end

  def destroy
    @gear = Gear.find(params[:id])
    @gear.destroy
    redirect_to user_my_gear_path(@user), notice: "Gear was successfully destroyed."
  end

  private

  def set_user
    @user = current_user
  end

  def gear_params
    params.require(:gear).permit(:gear_type, :gear_name, :total_occupancy, :summary, :address, :price, :latitude, :longitude, photos: [])
  end
end

app/views/gears/_edit.html.erb
<div class="container container-small">
  <%= simple_form_for [@gear] do |form| %>
    <% if gear.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(gear.errors.count, "error") %> prohibited this gear from being saved:</h2>
        <ul>
          <% gear.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-2">
      <%= form.input :gear_type, as: :select, collection: %w(Hiking Rock-Climbing Cooking Sleeping Kayak Navigation Shelter Sleeping-Bags Hydration Navigation First-Aid Survival Illumination Repair-Kits), prompt: 'Select Gear Type', label: false %>
    </div>

    <div class="my-2">
      <%= form.input :gear_name, class: "" %>
    </div>

    <div class="my-2">
      <%= form.input :total_occupancy, class: "" %>
    </div>

    <div class="my-2">
      <%= form.input :summary, class: "" %>
    </div>

    <div class="my-2">
      <%= form.input :address, class: "" %>
    </div>

    <div class="my-2">
      <%= form.input :price, class: "" %>
    </div>

    <div class="my-2">
      <%= form.input :photos, as: :file, input_html: { multiple: true }%>
    </div>

    <div class="my-4 inline btn-submit d-flex justify-content-between">
      <%= link_to "Go Back", user_my_gear_path(@user), class: "btn-no-border-right btn btn-outline-dark w-100" %>
      <%= form.submit class: "btn btn-outline-dark w-100" %>
    </div>
  <% end %>
</div>

app/views/gears/_form.html.erb
<div class="row justify-content-center">
<h2 class="text-center text-main">Create My Gear</h2>
<div class="col-6">
<%= simple_form_for [@user, @gear] do |form| %>
  <% if gear.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(gear.errors.count, "error") %> prohibited this gear from being saved:</h2>
      <ul>
        <% gear.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.input :gear_type,
                collection: %w(Hiking Rock-Climbing Cooking Sleeping Kayak Navigation Shelter Sleeping-Bags Hydration Navigation First-Aid Survival Illumination Repair-Kits) ,
                input_html: { class: 'form-transparent'} %>
  <%= form.input :gear_name,
                  input_html: { class: 'form-transparent'} %>
  <%= form.input :total_occupancy,
                collection: 1..20,
                input_html: { class: 'form-transparent'}
                %>
  <%= form.input :summary,
                  input_html: { class: 'form-transparent'}
                  %>
  <%= form.input :address,
                input_html: { class: 'form-transparent'}
                 %>
  <%= form.input :price,
                  input_html: { class: 'form-transparent'}
                %>
  <%= form.input :photos, as: :file,
                  input_html: { multiple: true, class: 'form-transparent' } %>
  <%= form.submit class: "button-green w-100" %>
<% end %>
</div>

app/views/gears/edit.html.erb
<%= render "edit", gear: @gear %>

app/views/gears/index.html.erb
<h1>All Gears for Rent</h1><br>
  --------------------------
  <% @gears.each do |gear| %>
    <% if gear.user != current_user %>
      <li>
        Gear Type:<%= gear.gear_type %> <br>
        Summary:<%= gear.summary %> <br>
        Owner:<%= gear.user.first_name %> <br>
        $<%= gear.price %> <br>
        <%= link_to "See More", gear_path(gear) %> <br>
        <%= link_to "book this gear", new_gear_rental_path(gear) %> <br>
        --------------------------
      </li>
    <% end %>
  <% end %>

app/views/gears/new.html.erb
<%= render "form", gear: @gear %>
​

app/views/gears/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col">
      <div class="product-tumb">
          <% if @gear.photos.present? %>
            <%= cl_image_tag @gear.photos.first.key, crop: :fill, width: 500, height: 350 %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1628087235616-4e146afcd061?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=776&q=80" alt="">
          <% end %>
        </div>
      <div style="height: 120px;"></div>

    </div>
    <div class="col gear-card" >
      <div class="product-details">
        <div class="flex-container">
          <div class="product-catagory"><%= @gear.gear_type %></div>
          <div class="product-rating"><span>★</span> <%= rand(3.9..5.0).round(1) %></div>
        </div>
            <h4><%= @gear.gear_name %></h4>
            <p>by
            <a href=<%= user_path(@gear.user) %>><%= @gear.user.first_name %> <%= @gear.user.last_name %></a></p>
          <div>
            <p class="product-summary"><%= @gear.summary %> </p>
          </div>
          <div>
            <p class="my-3"style="font-size: 20px; letter-spacing: 1px; line-height: 100%; color: black;">$<span id="price"><%= @gear.price.round() %></span><small> per night</small></p>
          </div>
          <div class="my-5">
            <%= simple_form_for [@gear, @rental], data: {controller: 'flatpickr'} do |form| %>
              <div class="row justify-content-between flex-wrap">
                <div class="col-6">
                  <%= form.input :start_date, label: 'Pick-up date', as: :string, input_html: { data: { flatpickr_target: "startTime" }, class: "form-transparent" } %>
                </div>
                <div class="col-6">
                  <%= form.input :end_date, label: 'Return date', as: :string, input_html: { data: { flatpickr_target: "endTime" }, class: "form-transparent", id: 'end_time'} %>
                </div>
              </div>
                <h3 class="product-price">Total Price: <span id="totalprice">0</span> AUD</h3>
                <%= form.submit 'Book this gear', onclick: "confirm('Are you sure to book this gear?')", id: "submit",class:"button-green w-100"%>
            <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
      <div class="container">
        <div id="allreview">
          <h2>Reviews</h2>
          <% if @gear.reviews == [] %>
          <i style="font-size: 15px; font-weight: 500; line-height: 100%;">Book the gear and be the first to review.</i>
          <% else %>
            <ul class="list-group list-group-flush">
                <% @gear.reviews.each do |review| %>
                  <li class="list-group-item">
                  <%= User.find(review.user_id).first_name %>
                  <%= User.find(review.user_id).last_name %>
                  <div class="review-rating">
                  <% review.rating.to_i.times do %>
                  <label class="rating-color">★</label>
                  <% end %>
                  <% review.blank_stars.times do %>
                  <label>☆</label>
                  <% end %>
                  <%= review.message %>
                  </div>
                  <div class="row justify-content-between">
                    <div class="col-10">
                      <%= review.content %>
                    </div>
                  </div>
                  </li>
                <% end %>
            </ul>
          <% end %>
        </div>
      </div>
</div>